### ISSUE TITLE
Issue in bridge connection of polkadot and ethereum

### ISSUE THREAD

**Issue by firebeegit** [sygmaprotocol/sygma-core#12]
Hi Team,
we are trying to connect bridge between polkadot and ethereum in my local system(ubuntu 22.04). I don't know how to installation and any other guide here (https://github.com/sygmaprotocol/sygma-core#installation).please let me know any solution guides or instruction guide.

Thank you,

**Comment by mpetrun5** [comment]
This repo is not really production ready so I would advise against using it.
